import streamlit as st

# De grote dictionary
UI_TRANSLATIONS = {
    "nl": {
        "title": "📊 De Staakbarometer",
        "welcome_msg": "Welkom! Laat uw stem horen. Bent u de stille meerderheid?",
        "username_placeholder": "Email adres...",
        "btn_login": "Inloggen / Registreren",
        "btn_logout": "Uitloggen",
        "btn_back": "← Terug naar overzicht",
        "btn_view_vote": "Bekijk & Stem",
        "btn_confirm": "Stem Bevestigen",
        "sidebar_lang": "Kies Taal / Langue / Language",
        "status_voted": "✅ Gestemd",
        "status_not_voted": "⚪ Nog niet gestemd",
        "login_warning": "Vul een email en wachtwoord in.",
        "success_vote": "Uw mening is geregistreerd! Bedankt.",
        "error_vote_exists": "U heeft al gestemd voor dit event.",
        "header_events": "Toekomstige Stakingsevenementen",
        "sub_events": "Selecteer een evenement om uw mening te geven.",
        "header_position": "Wat is uw positie?",
        "desc_position": "Kies de optie die het beste bij uw situatie past:",
        "chart_title": "Huidige Barometer (Live Data)",
        "opt_strike_agree": "Ik staak en ben akkoord",
        "opt_strike_disagree": "Ik staak en ben niet akkoord",
        "opt_work_agree": "Ik werk en ben akkoord",
        "opt_work_disagree": "Ik werk en ben niet akkoord",
        "lbl_date": "Datum",
        "lbl_sector": "Sector",
        "tab_login": "Inloggen",
        "tab_register": "Registreren",
        "lbl_password_confirm": "Bevestig Wachtwoord",
        "btn_register": "Account Aanmaken",
        "btn_reset": "Wachtwoord Resetten",
        "msg_pwd_mismatch": "Wachtwoorden komen niet overeen.",
        "msg_reset_sent": "Indien dit adres bekend is, ontvangt u een email met instructies.",
        "lnk_forgot_pwd": "Wachtwoord vergeten?",
        "err_login_failed": "Login mislukt. Controleer uw gegevens.",
        "tab_active": "Actief",
        "tab_archive": "Archief",
        "status_closed": "🔒 Stemmen Gesloten",
        "err_voting_closed": "Het is niet meer mogelijk om op dit event te stemmen."
    },
    "fr": {
        "title": "📊 Le Baromètre de Grève",
        "welcome_msg": "Bienvenue! Faites entendre votre voix. Êtes-vous la majorité silencieuse?",
        "username_placeholder": "Adresse email...",
        "btn_login": "Se connecter / S'inscrire",
        "btn_logout": "Se déconnecter",
        "btn_back": "← Retour à l'aperçu",
        "btn_view_vote": "Voir & Voter",
        "btn_confirm": "Confirmer le vote",
        "sidebar_lang": "Kies Taal / Langue / Language",
        "status_voted": "✅ Voté",
        "status_not_voted": "⚪ Pas encore voté",
        "login_warning": "Veuillez entrer un email et un mot de passe.",
        "success_vote": "Votre opinion a été enregistrée! Merci.",
        "error_vote_exists": "Vous avez déjà voté pour cet événement.",
        "header_events": "Événements de grève futurs",
        "sub_events": "Sélectionnez un événement pour donner votre avis.",
        "header_position": "Quelle est votre position?",
        "desc_position": "Choisissez l'option qui correspond le mieux à votre situation:",
        "chart_title": "Baromètre Actuel (Données en direct)",
        "opt_strike_agree": "Je fais grève et je suis d'accord",
        "opt_strike_disagree": "Je fais grève et je ne suis pas d'accord",
        "opt_work_agree": "Je travaille et je suis d'accord",
        "opt_work_disagree": "Je travaille et je ne suis pas d'accord",
        "lbl_date": "Date",
        "lbl_sector": "Secteur",
        "tab_login": "Se connecter",
        "tab_register": "S'inscrire",
        "lbl_password_confirm": "Confirmer mot de passe",
        "btn_register": "Créer un compte",
        "btn_reset": "Réinitialiser mot de passe",
        "msg_pwd_mismatch": "Les mots de passe ne correspondent pas.",
        "msg_reset_sent": "Si l'adresse existe, vous recevrez un email.",
        "lnk_forgot_pwd": "Mot de passe oublié ?",
        "err_login_failed": "Échec de la connexion.",
        "tab_active": "Actif",
        "tab_archive": "Archives",
        "status_closed": "🔒 Votes Clos",
        "err_voting_closed": "Il n'est plus possible de voter pour cet événement."
    },
    "en": {
        "title": "📊 The Strike Barometer",
        "welcome_msg": "Welcome! Make your voice heard. Are you the silent majority?",
        "username_placeholder": "Email address...",
        "btn_login": "Log In / Register",
        "btn_logout": "Log Out",
        "btn_back": "← Back to overview",
        "btn_view_vote": "View & Vote",
        "btn_confirm": "Confirm Vote",
        "sidebar_lang": "Kies Taal / Langue / Language",
        "status_voted": "✅ Voted",
        "status_not_voted": "⚪ Not voted yet",
        "login_warning": "Please enter an email and password.",
        "success_vote": "Your opinion has been registered! Thank you.",
        "error_vote_exists": "You have already voted for this event.",
        "header_events": "Future Strike Events",
        "sub_events": "Select an event to share your opinion.",
        "header_position": "What is your position?",
        "desc_position": "Choose the option that fits your situation best:",
        "chart_title": "Current Barometer (Live Data)",
        "opt_strike_agree": "I strike and I agree",
        "opt_strike_disagree": "I strike and I disagree",
        "opt_work_agree": "I work and I agree",
        "opt_work_disagree": "I work and I disagree",
        "lbl_date": "Date",
        "lbl_sector": "Sector",
        "tab_login": "Login",
        "tab_register": "Register",
        "lbl_password_confirm": "Confirm Password",
        "btn_register": "Create Account",
        "btn_reset": "Reset Password",
        "msg_pwd_mismatch": "Passwords do not match.",
        "msg_reset_sent": "If valid, you will receive an email.",
        "lnk_forgot_pwd": "Forgot password?",
        "err_login_failed": "Login failed.",
        "tab_active": "Active",
        "tab_archive": "Archive",
        "status_closed": "🔒 Voting Closed",
        "err_voting_closed": "Voting is no longer possible for this event."
    }
}

def get_text(key):
    """Haalt tekst op basis van session_state taal"""
    lang = st.session_state.get('language', 'nl')
    texts = UI_TRANSLATIONS.get(lang, UI_TRANSLATIONS['nl'])
    return texts.get(key, key)